<?php
// admin/reports.php
require_once __DIR__ . '/../config/session.php';
require_once __DIR__ . '/../includes/auth_guard.php';
require_once __DIR__ . '/../includes/role_guard.php';

// Restricted to admin and staff
require_role(['admin', 'staff']);

$page_title = 'Reports Generator';
$active_menu = 'reports';

require_once __DIR__ . '/../config/database.php';
$pdo = Database::getInstance()->getConnection();

// Date range filters (default to first of current month to today)
$startDate = $_GET['start_date'] ?? date('Y-m-01');
$endDate = $_GET['end_date'] ?? date('Y-m-d');

try {
    // 1. Patient Count by Purok
    $purokStmt = $pdo->prepare("
        SELECT 
            COALESCE(purok, 'Unspecified') AS purok_name, 
            COUNT(*) AS count 
        FROM patients 
        WHERE is_archived = 0 AND DATE(created_at) BETWEEN ? AND ?
        GROUP BY purok_name 
        ORDER BY count DESC
    ");
    $purokStmt->execute([$startDate, $endDate]);
    $purokTally = $purokStmt->fetchAll();

    // 2. Patient Count by Sex
    $sexStmt = $pdo->prepare("
        SELECT 
            sex, 
            COUNT(*) AS count 
        FROM patients 
        WHERE is_archived = 0 AND DATE(created_at) BETWEEN ? AND ?
        GROUP BY sex
    ");
    $sexStmt->execute([$startDate, $endDate]);
    $sexTally = $sexStmt->fetchAll();

    // 3. Consultations/Health Records Count by Service Category
    $serviceStmt = $pdo->prepare("
        SELECT 
            st.service_name, 
            COUNT(hr.record_id) AS count 
        FROM health_records hr
        LEFT JOIN service_types st ON hr.service_id = st.service_id
        WHERE hr.is_archived = 0 AND hr.visit_date BETWEEN ? AND ?
        GROUP BY hr.service_id, st.service_name
        ORDER BY count DESC
    ");
    $serviceStmt->execute([$startDate, $endDate]);
    $serviceTally = $serviceStmt->fetchAll();

    // 4. Appointments by Status
    $appStmt = $pdo->prepare("
        SELECT 
            status, 
            COUNT(*) AS count 
        FROM appointments 
        WHERE is_archived = 0 AND appointment_date BETWEEN ? AND ?
        GROUP BY status
    ");
    $appStmt->execute([$startDate, $endDate]);
    $appTally = $appStmt->fetchAll();

    // 5. Daily Queue Tickets by Status
    $queueStmt = $pdo->prepare("
        SELECT 
            status, 
            COUNT(*) AS count 
        FROM queue 
        WHERE is_archived = 0 AND queue_date BETWEEN ? AND ?
        GROUP BY status
    ");
    $queueStmt->execute([$startDate, $endDate]);
    $queueTally = $queueStmt->fetchAll();

} catch (Exception $e) {
    error_log("Failed to load reports: " . $e->getMessage());
    $purokTally = [];
    $sexTally = [];
    $serviceTally = [];
    $appTally = [];
    $queueTally = [];
}

require_once __DIR__ . '/../includes/header.php';
require_once __DIR__ . '/../includes/sidebar.php';
?>

<style>
/* Print stylesheet embedding */
@media print {
    #sidebar, 
    .top-navbar, 
    .page-header, 
    .filter-card, 
    .btn, 
    footer,
    #toggleSidebar {
        display: none !important;
    }
    
    body {
        background: #ffffff !important;
        color: #000000 !important;
        padding: 0 !important;
        margin: 0 !important;
    }
    
    .main-content {
        margin: 0 !important;
        padding: 0 !important;
        width: 100% !important;
    }
    
    .card-custom {
        box-shadow: none !important;
        border: 1px solid #ccc !important;
        background: #ffffff !important;
        margin-bottom: 20px !important;
        page-break-inside: avoid;
    }
    
    .row {
        display: flex !important;
        flex-wrap: wrap !important;
    }
    
    .col-md-6 {
        width: 50% !important;
        flex: 0 0 50% !important;
        max-width: 50% !important;
    }
    
    .col-lg-6 {
        width: 50% !important;
        flex: 0 0 50% !important;
        max-width: 50% !important;
    }

    .print-header {
        display: block !important;
        text-align: center;
        margin-bottom: 30px;
        border-bottom: 2px solid #333;
        padding-bottom: 15px;
    }
}
@media screen {
    .print-header {
        display: none !important;
    }
}
</style>

<main class="main-content">
    
    <!-- Print-only Document Header -->
    <div class="print-header">
        <h2 class="fw-bold mb-1">BARANGAY SINALHAN HEALTH CENTER</h2>
        <h5 class="text-secondary mb-3">System Operations Summary Report</h5>
        <div class="small text-secondary">
            Reporting Date Range: <strong><?= htmlspecialchars($startDate) ?></strong> to <strong><?= htmlspecialchars($endDate) ?></strong><br>
            Generated By: <strong><?= htmlspecialchars($_SESSION['full_name'] ?? 'System User') ?> (<?= htmlspecialchars(ucfirst($_SESSION['role'] ?? 'User')) ?>)</strong> on <strong><?= date('Y-m-d h:i A') ?></strong>
        </div>
    </div>

    <!-- Page Header (Screen only) -->
    <div class="page-header flex-column flex-sm-row justify-content-between align-items-start align-items-sm-center gap-3">
        <div>
            <h2 class="page-title">Operational Reports & Tally</h2>
            <p class="text-secondary mb-0">Generate tallies for patient registrations, services, appointments, and daily queue metrics.</p>
        </div>
        <div>
            <button onclick="window.print();" class="btn btn-primary d-flex align-items-center gap-2 py-2 px-4 shadow-sm">
                <i class="bi bi-printer-fill"></i>
                <span>Print / Save PDF</span>
            </button>
        </div>
    </div>

    <!-- Filter Card (Screen only) -->
    <div class="card-custom filter-card mb-4">
        <div class="card-custom-body p-3">
            <form method="GET" action="<?= BASE_URL ?>admin/reports.php" class="row g-3 align-items-end">
                <div class="col-md-5">
                    <label for="start_date" class="form-label small fw-bold text-secondary">Start Date Filter</label>
                    <input type="date" name="start_date" id="start_date" class="form-control" value="<?= htmlspecialchars($startDate) ?>">
                </div>
                <div class="col-md-5">
                    <label for="end_date" class="form-label small fw-bold text-secondary">End Date Filter</label>
                    <input type="date" name="end_date" id="end_date" class="form-control" value="<?= htmlspecialchars($endDate) ?>">
                </div>
                <div class="col-md-2">
                    <button type="submit" class="btn btn-teal w-100 py-2 d-flex align-items-center justify-content-center gap-2">
                        <i class="bi bi-filter"></i>
                        <span>Apply Filter</span>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- Metrics Grid -->
    <div class="row">
        <!-- Demographics Column -->
        <div class="col-lg-6 mb-4">
            <!-- Purok Tally Card -->
            <div class="card-custom mb-4">
                <div class="card-custom-header">
                    <h3 class="card-custom-title"><i class="bi bi-geo-alt-fill text-primary"></i> Patient Tally by Purok/Zone</h3>
                </div>
                <div class="card-custom-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered align-middle mb-0">
                            <thead class="table-light">
                                <tr>
                                    <th>Purok / Zone</th>
                                    <th class="text-center" style="width: 120px;">Registrations</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (count($purokTally) > 0): ?>
                                    <?php $totalPurok = 0; ?>
                                    <?php foreach ($purokTally as $pt): ?>
                                        <tr>
                                            <td class="fw-bold text-dark"><?= htmlspecialchars($pt['purok_name']) ?></td>
                                            <td class="text-center fw-bold text-primary"><?= $pt['count'] ?></td>
                                        </tr>
                                        <?php $totalPurok += $pt['count']; ?>
                                    <?php endforeach; ?>
                                    <tr class="table-secondary fw-bold">
                                        <td>TOTAL ACTIVE PATIENTS</td>
                                        <td class="text-center"><?= $totalPurok ?></td>
                                    </tr>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="2" class="text-center text-muted">No records found within specified range.</td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Sex Tally Card -->
            <div class="card-custom">
                <div class="card-custom-header">
                    <h3 class="card-custom-title"><i class="bi bi-gender-ambiguous text-info"></i> Patient Tally by Sex</h3>
                </div>
                <div class="card-custom-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered align-middle mb-0">
                            <thead class="table-light">
                                <tr>
                                    <th>Sex / Gender Category</th>
                                    <th class="text-center" style="width: 120px;">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (count($sexTally) > 0): ?>
                                    <?php $totalSex = 0; ?>
                                    <?php foreach ($sexTally as $st): ?>
                                        <tr>
                                            <td class="fw-bold text-dark"><?= htmlspecialchars($st['sex']) ?></td>
                                            <td class="text-center fw-bold text-info"><?= $st['count'] ?></td>
                                        </tr>
                                        <?php $totalSex += $st['count']; ?>
                                    <?php endforeach; ?>
                                    <tr class="table-secondary fw-bold">
                                        <td>TOTAL Patients</td>
                                        <td class="text-center"><?= $totalSex ?></td>
                                    </tr>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="2" class="text-center text-muted">No records found.</td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- Health Services and System Columns -->
        <div class="col-lg-6 mb-4">
            
            <!-- Health Services / Consultations Tally -->
            <div class="card-custom mb-4">
                <div class="card-custom-header">
                    <h3 class="card-custom-title"><i class="bi bi-heart-pulse-fill text-danger"></i> Health Service Tally</h3>
                </div>
                <div class="card-custom-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered align-middle mb-0">
                            <thead class="table-light">
                                <tr>
                                    <th>Service Name Category</th>
                                    <th class="text-center" style="width: 120px;">Consults</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (count($serviceTally) > 0): ?>
                                    <?php $totalServices = 0; ?>
                                    <?php foreach ($serviceTally as $st): ?>
                                        <tr>
                                            <td class="fw-bold text-dark"><?= htmlspecialchars($st['service_name'] ?? 'General Consultation') ?></td>
                                            <td class="text-center fw-bold text-danger"><?= $st['count'] ?></td>
                                        </tr>
                                        <?php $totalServices += $st['count']; ?>
                                    <?php endforeach; ?>
                                    <tr class="table-secondary fw-bold">
                                        <td>TOTAL CLINIC CONSULTATIONS</td>
                                        <td class="text-center"><?= $totalServices ?></td>
                                    </tr>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="2" class="text-center text-muted">No consultations logged.</td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Appointments & Queue Traffic Tally Grid -->
            <div class="row g-3">
                
                <!-- Appointments Tally -->
                <div class="col-md-6">
                    <div class="card-custom h-100 mb-0">
                        <div class="card-custom-header py-3">
                            <h3 class="card-custom-title text-accent" style="font-size: 15px;"><i class="bi bi-calendar-check-fill"></i> Appointments</h3>
                        </div>
                        <div class="card-custom-body py-2">
                            <table class="table table-sm table-bordered align-middle small mb-0">
                                <tbody>
                                    <?php $totalApp = 0; ?>
                                    <?php foreach ($appTally as $at): ?>
                                        <tr>
                                            <td><?= htmlspecialchars($at['status']) ?></td>
                                            <td class="text-center fw-bold"><?= $at['count'] ?></td>
                                        </tr>
                                        <?php $totalApp += $at['count']; ?>
                                    <?php endforeach; ?>
                                    <tr class="table-light fw-bold">
                                        <td>TOTAL</td>
                                        <td class="text-center"><?= $totalApp ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <!-- Queue Traffic Tally -->
                <div class="col-md-6">
                    <div class="card-custom h-100 mb-0">
                        <div class="card-custom-header py-3">
                            <h3 class="card-custom-title text-warning" style="font-size: 15px;"><i class="bi bi-ticket-detailed-fill"></i> Queue Tickets</h3>
                        </div>
                        <div class="card-custom-body py-2">
                            <table class="table table-sm table-bordered align-middle small mb-0">
                                <tbody>
                                    <?php $totalQueue = 0; ?>
                                    <?php foreach ($queueTally as $qt): ?>
                                        <tr>
                                            <td><?= htmlspecialchars($qt['status']) ?></td>
                                            <td class="text-center fw-bold"><?= $qt['count'] ?></td>
                                        </tr>
                                        <?php $totalQueue += $qt['count']; ?>
                                    <?php endforeach; ?>
                                    <tr class="table-light fw-bold">
                                        <td>TOTAL</td>
                                        <td class="text-center"><?= $totalQueue ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
</main>

<?php
require_once __DIR__ . '/../includes/alert.php';
require_once __DIR__ . '/../includes/footer.php';
?>
